# Site settings
title: Amazon Affiliate Store
description: Amazon results from /r/AmazonUnder25, presented as an online store page.
baseurl: /amazon-affiliate-store
url: https://cloudstitch-examples.github.io
amazon_tag: YOUR_TAG_HERE
subreddit: AmazonUnder25

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - lib
collections:
  pages:
    output: true