# Site settings
title: Amazon Affiliate Store
description: Amazon results from /r/shutupandtakemymoney, presented as an online store page.
baseurl: /amazon-affiliate-store
url: https://cloudstitch-examples.github.io
amazon_tag: YOUR_TAG_HERE
subreddit: shutupandtakemymoney

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - lib